theme: jekyll-theme-cayman
logo: https://medresearch.umich.edu/sites/default/files/styles/large_16_9/public/2023-08/res_brcf_bioinformatics_dna_stock_blue.jpeg?h=2240b8e9&itok=qTB6xmd9
title: Bioinf site
